title: Tr&aelig;
tags: Set Design, 3D Stereography, Interactive, Generative, Peppers' Ghost, OpenFrameworks, Featured
partners: Johan Bichel Lindegaard, Deborah Vlaeymans
client: In Transit
date: May 2014
materials: Spectral filters, 3D glasses, projectors, plastic foil, bespoke software
github: {user:'olekristensen',repo:'Trae'}
lead: Stage sized stereographic Pepper's Ghost
project_url: http://in-transit.org/trae/
photocredits: Johan Bichel Lindegaard
appearances: 
  - 
    date: May 2014
    occasion: Click Festival 
    place: Kulturværftet, Elsinore
    url: http://clickfestival.dk/

content: |
  Træ is an audio-visual experiment with generative stereographic projections in a stage sized Pepper's Ghost illusion.
  
  In this setup the performer and the projected 3d graphics seem to share the same space.
  
  This project is a first step into an exploration of these possibilities and limitations in performance and concert situations.