title: Multiplicity
tags: Installation, Kinect, Light, Interactive, OpenFrameworks, Featured
partners: Obscura
date: Nov 2013
materials: Kinect, folded steel plate, projectors, custom software
github: {user:'olekristensen',repo:'Multiplicity'}
lead: Interactive Light Mapping Sculpture
photocredits: Ole Kristensen
appearances: 
  - 
    date: Nov 2013
    occasion: Permanent installation 
    place: Fremtidens Borgerhus, Vallensbæk
    url: #

content: |
  Moving in front of the sculpture modulates the reflected light. It looks as if people are themselves ligths, their color shining on the triangualar facets on the wall.
  
  Multiplicity was commissioned by Vallensbæk Municipality for their new combined service center, public library and citizens' house.
  
  In collaboration with obscura (dk) I proposed a sculpture consisting of a physical object, folded from laser-cut steel, a couple of projectors, a Kinect and a computer.
  
  The sculpture acts as a platform for interactive software artworks, the first permanent artwork, Multiplicity, becoming just one of the ways to reflect the citizens' movements in their new house.
  
  Credits go to Kyle McDonald for his work on Mapamok, an integral part of making this happen on a short notice.